language: go

go:
  - "1.11.x"

os:
  - linux

dist: trusty
sudo: false
install: true

env:
  global:
    - GOARCH=amd64
    - GO111MODULE=on
    - GOOS=linux
after_success:
  - bash <(curl -s https://codecov.io/bash)
